export const GET_ALL_IMPORTDETAIL = "GET_ALL_IMPORTDETAIL";
export const GET_ALL_IMPORTDETAIL_SAGA = "GET_ALL_IMPORTDETAIL_SAGA";
export const ADD_PRODUCT_TO_IMPORT = "ADD_PRODUCT_TO_IMPORT";
export const ADD_PRODUCT_TO_IMPORT_SAGA = "ADD_PRODUCT_TO_IMPORT_SAGA";
export const DELETE_IMPORT_DETAIL_SAGA = "DELETE_IMPORT_DETAIL_SAGA";
