export const GET_ALL_IMPORT = "GET_ALL_IMPORT";
export const GET_ALL_IMPORT_SAGA = "GET_ALL_IMPORT_SAGA";
export const CREATE_IMPORT = "CREATE_IMPORT";
export const CREATE_IMPORT_SAGA = "CREATE_IMPORT_SAGA";
export const GET_ID_IMPORT = "GET_ID_IMPORT";
export const DELETE_IMPORT = "DELETE_IMPORT";
export const DELETE_IMPORT_SAGA = "DELETE_IMPORT_SAGA";
