export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SAGA = "GET_ALL_PRODUCT_SAGA";
export const GET_ID_PRODUCT = "GET_ID_PRODUCT";
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT";
export const GET_DETAIL_PRODUCT_SAGA = "GET_DETAIL_PRODUCT_SAGA";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SAGA = "DELETE_PRODUCT_SAGA";
